name: Python Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Update system packages
        run: sudo apt-get update

      - name: Install Sox as needed by torchaudio
        run: sudo apt-get install -y sox libsox-dev libsox-fmt-all

      - name: Configure dynamic linker run-time bindings
        run: sudo ldconfig

      - name: Install dependencies, CPU instead of CUDA
        run: |
          python -m pip install --upgrade pip
          sed 's/+cu118//g' requirements.txt > requirements_tmp.txt
          pip install -r requirements_tmp.txt

      - name: Run tests
        run: pytest tests_pytest/
